apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ./charts

helmCharts:
  - name: nodelocaldns
    releaseName: nodelocaldns
    namespace: kube-system
    valuesFile: values.yaml
