apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert.yaml
  - gateway.yaml
  - httproute.yaml

helmGlobals:
  chartHome: ./charts

helmCharts:
  - name: nodelocaldns
    releaseName: nodelocaldns
    namespace: kube-system
    valuesFile: values.yaml
